# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@parcel/watcher-2.5.1" = {
      name = "_at_parcel_slash_watcher";
      packageName = "@parcel/watcher";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher/-/watcher-2.5.1.tgz";
        sha512 = "dfUnCxiN9H4ap84DvD2ubjw+3vUNpstxa0TneY/Paat8a3R4uQZDLSvWjmznAY/DoahqTHl9V46HF/Zs3F29pg==";
      };
    };
    "@parcel/watcher-android-arm64-2.5.1" = {
      name = "_at_parcel_slash_watcher-android-arm64";
      packageName = "@parcel/watcher-android-arm64";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-android-arm64/-/watcher-android-arm64-2.5.1.tgz";
        sha512 = "KF8+j9nNbUN8vzOFDpRMsaKBHZ/mcjEjMToVMJOhTozkDonQFFrRcfdLWn6yWKCmJKmdVxSgHiYvTCef4/qcBA==";
      };
    };
    "@parcel/watcher-darwin-arm64-2.5.1" = {
      name = "_at_parcel_slash_watcher-darwin-arm64";
      packageName = "@parcel/watcher-darwin-arm64";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-darwin-arm64/-/watcher-darwin-arm64-2.5.1.tgz";
        sha512 = "eAzPv5osDmZyBhou8PoF4i6RQXAfeKL9tjb3QzYuccXFMQU0ruIc/POh30ePnaOyD1UXdlKguHBmsTs53tVoPw==";
      };
    };
    "@parcel/watcher-darwin-x64-2.5.1" = {
      name = "_at_parcel_slash_watcher-darwin-x64";
      packageName = "@parcel/watcher-darwin-x64";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-darwin-x64/-/watcher-darwin-x64-2.5.1.tgz";
        sha512 = "1ZXDthrnNmwv10A0/3AJNZ9JGlzrF82i3gNQcWOzd7nJ8aj+ILyW1MTxVk35Db0u91oD5Nlk9MBiujMlwmeXZg==";
      };
    };
    "@parcel/watcher-freebsd-x64-2.5.1" = {
      name = "_at_parcel_slash_watcher-freebsd-x64";
      packageName = "@parcel/watcher-freebsd-x64";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-freebsd-x64/-/watcher-freebsd-x64-2.5.1.tgz";
        sha512 = "SI4eljM7Flp9yPuKi8W0ird8TI/JK6CSxju3NojVI6BjHsTyK7zxA9urjVjEKJ5MBYC+bLmMcbAWlZ+rFkLpJQ==";
      };
    };
    "@parcel/watcher-linux-arm-glibc-2.5.1" = {
      name = "_at_parcel_slash_watcher-linux-arm-glibc";
      packageName = "@parcel/watcher-linux-arm-glibc";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-linux-arm-glibc/-/watcher-linux-arm-glibc-2.5.1.tgz";
        sha512 = "RCdZlEyTs8geyBkkcnPWvtXLY44BCeZKmGYRtSgtwwnHR4dxfHRG3gR99XdMEdQ7KeiDdasJwwvNSF5jKtDwdA==";
      };
    };
    "@parcel/watcher-linux-arm-musl-2.5.1" = {
      name = "_at_parcel_slash_watcher-linux-arm-musl";
      packageName = "@parcel/watcher-linux-arm-musl";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-linux-arm-musl/-/watcher-linux-arm-musl-2.5.1.tgz";
        sha512 = "6E+m/Mm1t1yhB8X412stiKFG3XykmgdIOqhjWj+VL8oHkKABfu/gjFj8DvLrYVHSBNC+/u5PeNrujiSQ1zwd1Q==";
      };
    };
    "@parcel/watcher-linux-arm64-glibc-2.5.1" = {
      name = "_at_parcel_slash_watcher-linux-arm64-glibc";
      packageName = "@parcel/watcher-linux-arm64-glibc";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-linux-arm64-glibc/-/watcher-linux-arm64-glibc-2.5.1.tgz";
        sha512 = "LrGp+f02yU3BN9A+DGuY3v3bmnFUggAITBGriZHUREfNEzZh/GO06FF5u2kx8x+GBEUYfyTGamol4j3m9ANe8w==";
      };
    };
    "@parcel/watcher-linux-arm64-musl-2.5.1" = {
      name = "_at_parcel_slash_watcher-linux-arm64-musl";
      packageName = "@parcel/watcher-linux-arm64-musl";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-linux-arm64-musl/-/watcher-linux-arm64-musl-2.5.1.tgz";
        sha512 = "cFOjABi92pMYRXS7AcQv9/M1YuKRw8SZniCDw0ssQb/noPkRzA+HBDkwmyOJYp5wXcsTrhxO0zq1U11cK9jsFg==";
      };
    };
    "@parcel/watcher-linux-x64-glibc-2.5.1" = {
      name = "_at_parcel_slash_watcher-linux-x64-glibc";
      packageName = "@parcel/watcher-linux-x64-glibc";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-linux-x64-glibc/-/watcher-linux-x64-glibc-2.5.1.tgz";
        sha512 = "GcESn8NZySmfwlTsIur+49yDqSny2IhPeZfXunQi48DMugKeZ7uy1FX83pO0X22sHntJ4Ub+9k34XQCX+oHt2A==";
      };
    };
    "@parcel/watcher-linux-x64-musl-2.5.1" = {
      name = "_at_parcel_slash_watcher-linux-x64-musl";
      packageName = "@parcel/watcher-linux-x64-musl";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-linux-x64-musl/-/watcher-linux-x64-musl-2.5.1.tgz";
        sha512 = "n0E2EQbatQ3bXhcH2D1XIAANAcTZkQICBPVaxMeaCVBtOpBZpWJuf7LwyWPSBDITb7In8mqQgJ7gH8CILCURXg==";
      };
    };
    "@parcel/watcher-win32-arm64-2.5.1" = {
      name = "_at_parcel_slash_watcher-win32-arm64";
      packageName = "@parcel/watcher-win32-arm64";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-win32-arm64/-/watcher-win32-arm64-2.5.1.tgz";
        sha512 = "RFzklRvmc3PkjKjry3hLF9wD7ppR4AKcWNzH7kXR7GUe0Igb3Nz8fyPwtZCSquGrhU5HhUNDr/mKBqj7tqA2Vw==";
      };
    };
    "@parcel/watcher-win32-ia32-2.5.1" = {
      name = "_at_parcel_slash_watcher-win32-ia32";
      packageName = "@parcel/watcher-win32-ia32";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-win32-ia32/-/watcher-win32-ia32-2.5.1.tgz";
        sha512 = "c2KkcVN+NJmuA7CGlaGD1qJh1cLfDnQsHjE89E60vUEMlqduHGCdCLJCID5geFVM0dOtA3ZiIO8BoEQmzQVfpQ==";
      };
    };
    "@parcel/watcher-win32-x64-2.5.1" = {
      name = "_at_parcel_slash_watcher-win32-x64";
      packageName = "@parcel/watcher-win32-x64";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@parcel/watcher-win32-x64/-/watcher-win32-x64-2.5.1.tgz";
        sha512 = "9lHBdJITeNR++EvSQVUcaZoWupyHfXe1jZvGZ06O/5MflPcuPLtEphScIBL+AiCWBO46tDSHzWyD0uDmmZqsgA==";
      };
    };
    "@tailwindcss/cli-4.0.8" = {
      name = "_at_tailwindcss_slash_cli";
      packageName = "@tailwindcss/cli";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/cli/-/cli-4.0.8.tgz";
        sha512 = "nFN0QjibH8Yhd028TP+WnStfEG0Bw9uS8ojqJNeEo4RfXH8Mfi42Y9lvhl3yPcii8/xt0/Mq/kZywjvpkcgLJg==";
      };
    };
    "@tailwindcss/node-4.0.8" = {
      name = "_at_tailwindcss_slash_node";
      packageName = "@tailwindcss/node";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/node/-/node-4.0.8.tgz";
        sha512 = "FKArQpbrbwv08TNT0k7ejYXpF+R8knZFAatNc0acOxbgeqLzwb86r+P3LGOjIeI3Idqe9CVkZrh4GlsJLJKkkw==";
      };
    };
    "@tailwindcss/oxide-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide";
      packageName = "@tailwindcss/oxide";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide/-/oxide-4.0.8.tgz";
        sha512 = "KfMcuAu/Iw+DcV1e8twrFyr2yN8/ZDC/odIGta4wuuJOGkrkHZbvJvRNIbQNhGh7erZTYV6Ie0IeD6WC9Y8Hcw==";
      };
    };
    "@tailwindcss/oxide-android-arm64-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-android-arm64";
      packageName = "@tailwindcss/oxide-android-arm64";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-android-arm64/-/oxide-android-arm64-4.0.8.tgz";
        sha512 = "We7K79+Sm4mwJHk26Yzu/GAj7C7myemm7PeXvpgMxyxO70SSFSL3uCcqFbz9JA5M5UPkrl7N9fkBe/Y0iazqpA==";
      };
    };
    "@tailwindcss/oxide-darwin-arm64-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-darwin-arm64";
      packageName = "@tailwindcss/oxide-darwin-arm64";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-darwin-arm64/-/oxide-darwin-arm64-4.0.8.tgz";
        sha512 = "Lv9Isi2EwkCTG1sRHNDi0uRNN1UGFdEThUAGFrydRmQZnraGLMjN8gahzg2FFnOizDl7LB2TykLUuiw833DSNg==";
      };
    };
    "@tailwindcss/oxide-darwin-x64-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-darwin-x64";
      packageName = "@tailwindcss/oxide-darwin-x64";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-darwin-x64/-/oxide-darwin-x64-4.0.8.tgz";
        sha512 = "fWfywfYIlSWtKoqWTjukTHLWV3ARaBRjXCC2Eo0l6KVpaqGY4c2y8snUjp1xpxUtpqwMvCvFWFaleMoz1Vhzlw==";
      };
    };
    "@tailwindcss/oxide-freebsd-x64-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-freebsd-x64";
      packageName = "@tailwindcss/oxide-freebsd-x64";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-freebsd-x64/-/oxide-freebsd-x64-4.0.8.tgz";
        sha512 = "SO+dyvjJV9G94bnmq2288Ke0BIdvrbSbvtPLaQdqjqHR83v5L2fWADyFO+1oecHo9Owsk8MxcXh1agGVPIKIqw==";
      };
    };
    "@tailwindcss/oxide-linux-arm-gnueabihf-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-linux-arm-gnueabihf";
      packageName = "@tailwindcss/oxide-linux-arm-gnueabihf";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-linux-arm-gnueabihf/-/oxide-linux-arm-gnueabihf-4.0.8.tgz";
        sha512 = "ZSHggWiEblQNV69V0qUK5vuAtHP+I+S2eGrKGJ5lPgwgJeAd6GjLsVBN+Mqn2SPVfYM3BOpS9jX/zVg9RWQVDQ==";
      };
    };
    "@tailwindcss/oxide-linux-arm64-gnu-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-linux-arm64-gnu";
      packageName = "@tailwindcss/oxide-linux-arm64-gnu";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-linux-arm64-gnu/-/oxide-linux-arm64-gnu-4.0.8.tgz";
        sha512 = "xWpr6M0OZLDNsr7+bQz+3X7zcnDJZJ1N9gtBWCtfhkEtDjjxYEp+Lr5L5nc/yXlL4MyCHnn0uonGVXy3fhxaVA==";
      };
    };
    "@tailwindcss/oxide-linux-arm64-musl-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-linux-arm64-musl";
      packageName = "@tailwindcss/oxide-linux-arm64-musl";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-linux-arm64-musl/-/oxide-linux-arm64-musl-4.0.8.tgz";
        sha512 = "5tz2IL7LN58ssGEq7h/staD7pu/izF/KeMWdlJ86WDe2Ah46LF3ET6ZGKTr5eZMrnEA0M9cVFuSPprKRHNgjeg==";
      };
    };
    "@tailwindcss/oxide-linux-x64-gnu-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-linux-x64-gnu";
      packageName = "@tailwindcss/oxide-linux-x64-gnu";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-linux-x64-gnu/-/oxide-linux-x64-gnu-4.0.8.tgz";
        sha512 = "KSzMkhyrxAQyY2o194NKVKU9j/c+NFSoMvnHWFaNHKi3P1lb+Vq1UC19tLHrmxSkKapcMMu69D7+G1+FVGNDXQ==";
      };
    };
    "@tailwindcss/oxide-linux-x64-musl-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-linux-x64-musl";
      packageName = "@tailwindcss/oxide-linux-x64-musl";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-linux-x64-musl/-/oxide-linux-x64-musl-4.0.8.tgz";
        sha512 = "yFYKG5UtHTRimjtqxUWXBgI4Tc6NJe3USjRIVdlTczpLRxq/SFwgzGl5JbatCxgSRDPBFwRrNPxq+ukfQFGdrw==";
      };
    };
    "@tailwindcss/oxide-win32-arm64-msvc-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-win32-arm64-msvc";
      packageName = "@tailwindcss/oxide-win32-arm64-msvc";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-win32-arm64-msvc/-/oxide-win32-arm64-msvc-4.0.8.tgz";
        sha512 = "tndGujmCSba85cRCnQzXgpA2jx5gXimyspsUYae5jlPyLRG0RjXbDshFKOheVXU4TLflo7FSG8EHCBJ0EHTKdQ==";
      };
    };
    "@tailwindcss/oxide-win32-x64-msvc-4.0.8" = {
      name = "_at_tailwindcss_slash_oxide-win32-x64-msvc";
      packageName = "@tailwindcss/oxide-win32-x64-msvc";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@tailwindcss/oxide-win32-x64-msvc/-/oxide-win32-x64-msvc-4.0.8.tgz";
        sha512 = "T77jroAc0p4EHVVgTUiNeFn6Nj3jtD3IeNId2X+0k+N1XxfNipy81BEkYErpKLiOkNhpNFjPee8/ZVas29b2OQ==";
      };
    };
    "braces-3.0.3" = {
      name = "braces";
      packageName = "braces";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/braces/-/braces-3.0.3.tgz";
        sha512 = "yQbXgO/OSZVD2IsiLlro+7Hf6Q18EJrKSEsdoMzKePKXct3gvD8oLcOQdIzGupr5Fj+EDe8gO/lxc1BzfMpxvA==";
      };
    };
    "daisyui-5.0.0-beta.8" = {
      name = "daisyui";
      packageName = "daisyui";
      version = "5.0.0-beta.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/daisyui/-/daisyui-5.0.0-beta.8.tgz";
        sha512 = "jSokqm5i+Pv1jG80wliNzMHjmcF+iMx5xRUpk0/QExVoVNyQNWeCsaWJQubPvUq7bt9nzSsQTR2uIZBoyIIoaA==";
      };
    };
    "detect-libc-1.0.3" = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-1.0.3.tgz";
        sha512 = "pGjwhsmsp4kL2RTz08wcOlGN83otlqHeD/Z5T8GXZB+/YcpQ/dgo+lbU8ZsGxV0HIvqqxo9l7mqYwyYMD9bKDg==";
      };
    };
    "enhanced-resolve-5.18.1" = {
      name = "enhanced-resolve";
      packageName = "enhanced-resolve";
      version = "5.18.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-5.18.1.tgz";
        sha512 = "ZSW3ma5GkcQBIpwZTSRAI8N71Uuwgs93IezB7mf7R60tC8ZbJideoDNKjHn2O9KIlx6rkGTTEk1xUCK2E1Y2Yg==";
      };
    };
    "fill-range-7.1.1" = {
      name = "fill-range";
      packageName = "fill-range";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fill-range/-/fill-range-7.1.1.tgz";
        sha512 = "YsGpe3WHLK8ZYi4tWDg2Jy3ebRz2rXowDxnld4bkQB00cc/1Zw9AWnC0i9ztDJitivtQvaI9KaLyKrc+hBW0yg==";
      };
    };
    "graceful-fs-4.2.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.2.11.tgz";
        sha512 = "RbJ5/jmFcNNCcDV5o9eTnBLJ/HszWV0P73bc+Ff4nS/rJj+YaS6IGyiOL0VoBYX+l1Wrl3k63h/KrH+nhJ0XvQ==";
      };
    };
    "is-extglob-2.1.1" = {
      name = "is-extglob";
      packageName = "is-extglob";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-extglob/-/is-extglob-2.1.1.tgz";
        sha512 = "SbKbANkN603Vi4jEZv49LeVJMn4yGwsbzZworEoyEiutsN3nJYdbO36zfhGJ6QEDpOZIFkDtnq5JRxmvl3jsoQ==";
      };
    };
    "is-glob-4.0.3" = {
      name = "is-glob";
      packageName = "is-glob";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-glob/-/is-glob-4.0.3.tgz";
        sha512 = "xelSayHH36ZgE7ZWhli7pW34hNbNl8Ojv5KVmkJD4hBdD3th8Tfk9vYasLM+mXWOZhFkgZfxhLSnrwRr4elSSg==";
      };
    };
    "is-number-7.0.0" = {
      name = "is-number";
      packageName = "is-number";
      version = "7.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-number/-/is-number-7.0.0.tgz";
        sha512 = "41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==";
      };
    };
    "jiti-2.4.2" = {
      name = "jiti";
      packageName = "jiti";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jiti/-/jiti-2.4.2.tgz";
        sha512 = "rg9zJN+G4n2nfJl5MW3BMygZX56zKPNVEYYqq7adpmMh4Jn2QNEwhvQlFy6jPVdcod7txZtKHWnyZiA3a0zP7A==";
      };
    };
    "lightningcss-1.29.1" = {
      name = "lightningcss";
      packageName = "lightningcss";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss/-/lightningcss-1.29.1.tgz";
        sha512 = "FmGoeD4S05ewj+AkhTY+D+myDvXI6eL27FjHIjoyUkO/uw7WZD1fBVs0QxeYWa7E17CUHJaYX/RUGISCtcrG4Q==";
      };
    };
    "lightningcss-darwin-arm64-1.29.1" = {
      name = "lightningcss-darwin-arm64";
      packageName = "lightningcss-darwin-arm64";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-darwin-arm64/-/lightningcss-darwin-arm64-1.29.1.tgz";
        sha512 = "HtR5XJ5A0lvCqYAoSv2QdZZyoHNttBpa5EP9aNuzBQeKGfbyH5+UipLWvVzpP4Uml5ej4BYs5I9Lco9u1fECqw==";
      };
    };
    "lightningcss-darwin-x64-1.29.1" = {
      name = "lightningcss-darwin-x64";
      packageName = "lightningcss-darwin-x64";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-darwin-x64/-/lightningcss-darwin-x64-1.29.1.tgz";
        sha512 = "k33G9IzKUpHy/J/3+9MCO4e+PzaFblsgBjSGlpAaFikeBFm8B/CkO3cKU9oI4g+fjS2KlkLM/Bza9K/aw8wsNA==";
      };
    };
    "lightningcss-freebsd-x64-1.29.1" = {
      name = "lightningcss-freebsd-x64";
      packageName = "lightningcss-freebsd-x64";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-freebsd-x64/-/lightningcss-freebsd-x64-1.29.1.tgz";
        sha512 = "0SUW22fv/8kln2LnIdOCmSuXnxgxVC276W5KLTwoehiO0hxkacBxjHOL5EtHD8BAXg2BvuhsJPmVMasvby3LiQ==";
      };
    };
    "lightningcss-linux-arm-gnueabihf-1.29.1" = {
      name = "lightningcss-linux-arm-gnueabihf";
      packageName = "lightningcss-linux-arm-gnueabihf";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-linux-arm-gnueabihf/-/lightningcss-linux-arm-gnueabihf-1.29.1.tgz";
        sha512 = "sD32pFvlR0kDlqsOZmYqH/68SqUMPNj+0pucGxToXZi4XZgZmqeX/NkxNKCPsswAXU3UeYgDSpGhu05eAufjDg==";
      };
    };
    "lightningcss-linux-arm64-gnu-1.29.1" = {
      name = "lightningcss-linux-arm64-gnu";
      packageName = "lightningcss-linux-arm64-gnu";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-linux-arm64-gnu/-/lightningcss-linux-arm64-gnu-1.29.1.tgz";
        sha512 = "0+vClRIZ6mmJl/dxGuRsE197o1HDEeeRk6nzycSy2GofC2JsY4ifCRnvUWf/CUBQmlrvMzt6SMQNMSEu22csWQ==";
      };
    };
    "lightningcss-linux-arm64-musl-1.29.1" = {
      name = "lightningcss-linux-arm64-musl";
      packageName = "lightningcss-linux-arm64-musl";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-linux-arm64-musl/-/lightningcss-linux-arm64-musl-1.29.1.tgz";
        sha512 = "UKMFrG4rL/uHNgelBsDwJcBqVpzNJbzsKkbI3Ja5fg00sgQnHw/VrzUTEc4jhZ+AN2BvQYz/tkHu4vt1kLuJyw==";
      };
    };
    "lightningcss-linux-x64-gnu-1.29.1" = {
      name = "lightningcss-linux-x64-gnu";
      packageName = "lightningcss-linux-x64-gnu";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-linux-x64-gnu/-/lightningcss-linux-x64-gnu-1.29.1.tgz";
        sha512 = "u1S+xdODy/eEtjADqirA774y3jLcm8RPtYztwReEXoZKdzgsHYPl0s5V52Tst+GKzqjebkULT86XMSxejzfISw==";
      };
    };
    "lightningcss-linux-x64-musl-1.29.1" = {
      name = "lightningcss-linux-x64-musl";
      packageName = "lightningcss-linux-x64-musl";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-linux-x64-musl/-/lightningcss-linux-x64-musl-1.29.1.tgz";
        sha512 = "L0Tx0DtaNUTzXv0lbGCLB/c/qEADanHbu4QdcNOXLIe1i8i22rZRpbT3gpWYsCh9aSL9zFujY/WmEXIatWvXbw==";
      };
    };
    "lightningcss-win32-arm64-msvc-1.29.1" = {
      name = "lightningcss-win32-arm64-msvc";
      packageName = "lightningcss-win32-arm64-msvc";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-win32-arm64-msvc/-/lightningcss-win32-arm64-msvc-1.29.1.tgz";
        sha512 = "QoOVnkIEFfbW4xPi+dpdft/zAKmgLgsRHfJalEPYuJDOWf7cLQzYg0DEh8/sn737FaeMJxHZRc1oBreiwZCjog==";
      };
    };
    "lightningcss-win32-x64-msvc-1.29.1" = {
      name = "lightningcss-win32-x64-msvc";
      packageName = "lightningcss-win32-x64-msvc";
      version = "1.29.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lightningcss-win32-x64-msvc/-/lightningcss-win32-x64-msvc-1.29.1.tgz";
        sha512 = "NygcbThNBe4JElP+olyTI/doBNGJvLs3bFCRPdvuCcxZCcCZ71B858IHpdm7L1btZex0FvCmM17FK98Y9MRy1Q==";
      };
    };
    "micromatch-4.0.8" = {
      name = "micromatch";
      packageName = "micromatch";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromatch/-/micromatch-4.0.8.tgz";
        sha512 = "PXwfBhYu0hBCPw8Dn0E+WDYb7af3dSLVWKi3HGv84IdF4TyFoC0ysxFd0Goxw7nSv4T/PzEJQxsYsEiFCKo2BA==";
      };
    };
    "mri-1.2.0" = {
      name = "mri";
      packageName = "mri";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mri/-/mri-1.2.0.tgz";
        sha512 = "tzzskb3bG8LvYGFF/mDTpq3jpI6Q9wc3LEmBaghu+DdCssd1FakN7Bc0hVNmEyGq1bq3RgfkCb3cmQLpNPOroA==";
      };
    };
    "node-addon-api-7.1.1" = {
      name = "node-addon-api";
      packageName = "node-addon-api";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-addon-api/-/node-addon-api-7.1.1.tgz";
        sha512 = "5m3bsyrjFWE1xf7nz7YXdN4udnVtXK6/Yfgn5qnahL6bCkf2yKt4k3nuTKAtT4r3IG8JNR2ncsIMdZuAzJjHQQ==";
      };
    };
    "picocolors-1.1.1" = {
      name = "picocolors";
      packageName = "picocolors";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picocolors/-/picocolors-1.1.1.tgz";
        sha512 = "xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "tailwindcss-4.0.8" = {
      name = "tailwindcss";
      packageName = "tailwindcss";
      version = "4.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/tailwindcss/-/tailwindcss-4.0.8.tgz";
        sha512 = "Me7N5CKR+D2A1xdWA5t5+kjjT7bwnxZOE6/yDI/ixJdJokszsn2n++mdU5yJwrsTpqFX2B9ZNMBJDwcqk9C9lw==";
      };
    };
    "tapable-2.2.1" = {
      name = "tapable";
      packageName = "tapable";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tapable/-/tapable-2.2.1.tgz";
        sha512 = "GNzQvQTOIP6RyTfE2Qxb8ZVlNmw0n88vp1szwWRimP02mnTsx3Wtn5qRdqY9w2XduFNUgvOwhNnQsjwCp+kqaQ==";
      };
    };
    "to-regex-range-5.0.1" = {
      name = "to-regex-range";
      packageName = "to-regex-range";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/to-regex-range/-/to-regex-range-5.0.1.tgz";
        sha512 = "65P7iz6X5yEr1cwcgvQxbbIw7Uk3gOy5dIdtZ4rDveLqhrdJP+Li/Hx6tyK0NEb+2GCyneCMJiGqrADCSNk8sQ==";
      };
    };
  };
  args = {
    name = "tailwindcss-daisyui";
    packageName = "tailwindcss-daisyui";
    src = ./.;
    dependencies = [
      sources."@parcel/watcher-2.5.1"
      sources."@parcel/watcher-android-arm64-2.5.1"
      sources."@parcel/watcher-darwin-arm64-2.5.1"
      sources."@parcel/watcher-darwin-x64-2.5.1"
      sources."@parcel/watcher-freebsd-x64-2.5.1"
      sources."@parcel/watcher-linux-arm-glibc-2.5.1"
      sources."@parcel/watcher-linux-arm-musl-2.5.1"
      sources."@parcel/watcher-linux-arm64-glibc-2.5.1"
      sources."@parcel/watcher-linux-arm64-musl-2.5.1"
      sources."@parcel/watcher-linux-x64-glibc-2.5.1"
      sources."@parcel/watcher-linux-x64-musl-2.5.1"
      sources."@parcel/watcher-win32-arm64-2.5.1"
      sources."@parcel/watcher-win32-ia32-2.5.1"
      sources."@parcel/watcher-win32-x64-2.5.1"
      sources."@tailwindcss/cli-4.0.8"
      sources."@tailwindcss/node-4.0.8"
      sources."@tailwindcss/oxide-4.0.8"
      sources."@tailwindcss/oxide-android-arm64-4.0.8"
      sources."@tailwindcss/oxide-darwin-arm64-4.0.8"
      sources."@tailwindcss/oxide-darwin-x64-4.0.8"
      sources."@tailwindcss/oxide-freebsd-x64-4.0.8"
      sources."@tailwindcss/oxide-linux-arm-gnueabihf-4.0.8"
      sources."@tailwindcss/oxide-linux-arm64-gnu-4.0.8"
      sources."@tailwindcss/oxide-linux-arm64-musl-4.0.8"
      sources."@tailwindcss/oxide-linux-x64-gnu-4.0.8"
      sources."@tailwindcss/oxide-linux-x64-musl-4.0.8"
      sources."@tailwindcss/oxide-win32-arm64-msvc-4.0.8"
      sources."@tailwindcss/oxide-win32-x64-msvc-4.0.8"
      sources."braces-3.0.3"
      sources."daisyui-5.0.0-beta.8"
      sources."detect-libc-1.0.3"
      sources."enhanced-resolve-5.18.1"
      sources."fill-range-7.1.1"
      sources."graceful-fs-4.2.11"
      sources."is-extglob-2.1.1"
      sources."is-glob-4.0.3"
      sources."is-number-7.0.0"
      sources."jiti-2.4.2"
      sources."lightningcss-1.29.1"
      sources."lightningcss-darwin-arm64-1.29.1"
      sources."lightningcss-darwin-x64-1.29.1"
      sources."lightningcss-freebsd-x64-1.29.1"
      sources."lightningcss-linux-arm-gnueabihf-1.29.1"
      sources."lightningcss-linux-arm64-gnu-1.29.1"
      sources."lightningcss-linux-arm64-musl-1.29.1"
      sources."lightningcss-linux-x64-gnu-1.29.1"
      sources."lightningcss-linux-x64-musl-1.29.1"
      sources."lightningcss-win32-arm64-msvc-1.29.1"
      sources."lightningcss-win32-x64-msvc-1.29.1"
      sources."micromatch-4.0.8"
      sources."mri-1.2.0"
      sources."node-addon-api-7.1.1"
      sources."picocolors-1.1.1"
      sources."picomatch-2.3.1"
      sources."tailwindcss-4.0.8"
      sources."tapable-2.2.1"
      sources."to-regex-range-5.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
